### ISSUE TITLE
Not loading brat ?

### ISSUE THREAD

**Issue by sgentile** [cassj/brat-docker#1]
Thanks for putting this together - when I hit the website it's not loading brat:

```
Index of /

[ICO]   Name    Last modified   Size    Description
Apache/2.4.18 (Ubuntu) Server at localhost
```

That is all I see - any suggestions ?

**Comment by cassj** [comment]
Hi Steve,

Sorry for taking a while to get back to you. I haven’t looked at this container for ages. I’ve just updated it a bit. Maybe try again? It seems to work for me on my mac using docker-machine (docker 1.9.0). If it’s still causing you problems, could you give me some more info? What docker version are you using? What docker run command are you using? Is there any useful output from docker logs?

Cheers,
Cass
