### ISSUE TITLE
Multiple users configuration

### ISSUE THREAD

**Issue by savkov** [cassj/brat-docker#2]
Hi,

Thanks for dockerising this! I needed to set up more than one user for my brat instance came up with an extension of your container. If you are willing to give me the access rights I would be happy to submit a pull request.

Thanks!

**Comment by cassj** [comment]
Merged. thanks! I've changed jobs and I'm not really using brat now, so I
haven't looked at this stuff for ages. The dockerhub image is configured to
automatically build, so https://hub.docker.com/r/cassj/brat/ should now
reflect your changes.

C xx

**Comment by savkov** [comment]
Thanks!
