### ISSUE TITLE
I try to add users but it doesn't work

### ISSUE THREAD

**Issue by simonmeoni** [cassj/brat-docker#5]
I linked bratcfg with a folder contain a users.json well formed (like the example) but no users are added during the running of the container. I was missed a step ?
Thanks in advance

**Comment by cassj** [comment]
Am not doing anything with brat any more so I haven't looked at this for ages. I might have time to take a look at the weekend, but it was @savkov who did the multi-user config so he might be more help in the meantime...

**Comment by savkov** [comment]
@simonmeoni can you show us the docker command you are running? Also, make sure that the file can be read by the user inside the container. The server most likely runs under `www-data`.

**Comment by simonmeoni** [comment]
i run this command : `sudo docker run --name=brat -d -p 80:80 -v brat-data:/bratdata -v brat-cfg:/bratcfg -e BRAT_USERNAME=brat -e BRAT_PASSWORD=brat -e BRAT_EMAIL=brat@example.com  cassj/brat`

I create two volume brat-cfg and brat-data, these both works.
I try to execute `python user_patch.py` inside the container 
and I get this :
 `Traceback (most recent call last):
  File "user_patch.py", line 7, in <module>
    usr_json = json.load(open('cfg/users.json', 'r'))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 4 column 1 (char 44)`

**Comment by simonmeoni** [comment]
Sorry, it was a blunder from me. I was forget to remove a comma inside my json file.
Everything works ! Thanks for your reactivity
